#pragma checksum "d:\IBIZWebApp\Shared\Toast.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3789c60d1410afbf044cf44b7b87f10f3c8380ce"
// <auto-generated/>
#pragma warning disable 1591
namespace __GeneratedComponent
{
    #line hidden
#nullable restore
#line 1 "d:\IBIZWebApp\_Imports.razor"
using Microsoft.AspNetCore.Components;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "d:\IBIZWebApp\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "d:\IBIZWebApp\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "d:\IBIZWebApp\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "d:\IBIZWebApp\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "d:\IBIZWebApp\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "d:\IBIZWebApp\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "d:\IBIZWebApp\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "d:\IBIZWebApp\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "d:\IBIZWebApp\_Imports.razor"
using IBIZWebApp;

#line default
#line hidden
#nullable disable
#nullable restore
#line 11 "d:\IBIZWebApp\_Imports.razor"
using IBIZWebApp.Layout;

#line default
#line hidden
#nullable disable
    public partial class AspNetCore_3789c60d1410afbf044cf44b7b87f10f3c8380ce : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "class", "toast-container");
            __builder.AddAttribute(2, "style", "position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 9999; display: flex; flex-direction: column; align-items: center;");
#nullable restore
#line 4 "d:\IBIZWebApp\Shared\Toast.razor"
     if (Visible)
    {

#line default
#line hidden
#nullable disable
            __builder.OpenElement(3, "div");
            __builder.AddAttribute(4, "class", "toast-message" + " " + (
#nullable restore
#line 6 "d:\IBIZWebApp\Shared\Toast.razor"
                                   ToastType

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(5, "style", "min-width:" + " 280px;" + " max-width:" + " 90vw;" + " padding:" + " 1rem" + " 1.5rem" + " 1.2rem" + " 1.5rem;" + " border-radius:" + " 12px;" + " margin-bottom:" + " 0.5rem;" + " box-shadow:" + " 0" + " 2px" + " 12px" + " rgba(0,0,0,0.10);" + " background:" + " #f8f9fa;" + " border-left:" + " 7px" + " solid" + " " + (
#nullable restore
#line 6 "d:\IBIZWebApp\Shared\Toast.razor"
                                                                                                                                                                                                                                                              BorderColor

#line default
#line hidden
#nullable disable
            ) + ";" + " text-align:" + " center;" + " font-size:" + " 0.98rem;" + " font-weight:" + " 400;" + " position:" + " relative;" + " color:" + " #222;");
            __builder.OpenElement(6, "div");
            __builder.AddAttribute(7, "style", "font-size:1.05rem; font-weight:500; margin-bottom:0.18rem; color:#333;");
#nullable restore
#line 7 "d:\IBIZWebApp\Shared\Toast.razor"
__builder.AddContent(8, Title);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
#nullable restore
#line 8 "d:\IBIZWebApp\Shared\Toast.razor"
             if (!string.IsNullOrEmpty(Message))
            {

#line default
#line hidden
#nullable disable
            __builder.OpenElement(9, "div");
            __builder.AddAttribute(10, "style", "margin-bottom:0.8rem; color:#444;");
#nullable restore
#line 10 "d:\IBIZWebApp\Shared\Toast.razor"
__builder.AddContent(11, Message);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
#nullable restore
#line 11 "d:\IBIZWebApp\Shared\Toast.razor"
            }

#line default
#line hidden
#nullable disable
            __builder.OpenElement(12, "button");
            __builder.AddAttribute(13, "@onclick", "HideToast");
            __builder.AddAttribute(14, "style", "padding:" + " 0.32rem" + " 1.1rem;" + " border-radius:" + " 5px;" + " border:" + " none;" + " background:" + " " + (
#nullable restore
#line 12 "d:\IBIZWebApp\Shared\Toast.razor"
                                                                                                                        BorderColor

#line default
#line hidden
#nullable disable
            ) + ";" + " color:" + " #fff;" + " font-weight:" + " 400;" + " font-size:" + " 0.97rem;" + " cursor:" + " pointer;" + " box-shadow:" + " 0" + " 1px" + " 4px" + " rgba(0,0,0,0.05);" + " transition:" + " background" + " 0.2s;");
            __builder.AddContent(15, "OK");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 14 "d:\IBIZWebApp\Shared\Toast.razor"
    }

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line 17 "d:\IBIZWebApp\Shared\Toast.razor"
       
    private string Title = "";
    private string Message = "";
    private string ToastType = "";
    private string BorderColor = "#007bff";
    private bool Visible = false;
    private System.Timers.Timer? timer;

    protected override void OnInitialized()
    {
        ToastService.OnShow += ShowToast;
    }

    private async Task ShowToast(string title, string message)
    {
        Title = title;
        Message = message;
        ToastType = GetToastType(title);
        BorderColor = GetBorderColor(title);
        Visible = true;
        StateHasChanged();
        timer?.Dispose();
        timer = new System.Timers.Timer(3500);
        timer.Elapsed += (s, e) => HideToast();
        timer.AutoReset = false;
        timer.Start();
    }

    private void HideToast()
    {
        Visible = false;
        StateHasChanged();
    }

    private string GetToastType(string title)
    {
        if (title.Contains("error", StringComparison.OrdinalIgnoreCase)) return "toast-error";
        if (title.Contains("success", StringComparison.OrdinalIgnoreCase)) return "toast-success";
        if (title.Contains("warning", StringComparison.OrdinalIgnoreCase)) return "toast-warning";
        if (title.Contains("info", StringComparison.OrdinalIgnoreCase)) return "toast-info";
        return "toast-info";
    }
    private string GetBorderColor(string title)
    {
        if (title.Contains("error", StringComparison.OrdinalIgnoreCase)) return "#dc3545";
        if (title.Contains("success", StringComparison.OrdinalIgnoreCase)) return "#28a745";
        if (title.Contains("warning", StringComparison.OrdinalIgnoreCase)) return "#ffc107";
        if (title.Contains("info", StringComparison.OrdinalIgnoreCase)) return "#17a2b8";
        return "#007bff";
    }

    public void Dispose()
    {
        ToastService.OnShow -= ShowToast;
        timer?.Dispose();
    }

#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private IBIZWebApp.Services.IToastService ToastService { get; set; }
    }
}
#pragma warning restore 1591
