name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Change to 'master' if that is your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Change to '9.0.x' if using .NET 9

    - name: Publish App
      run: dotnet publish -c Release -o release

    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'release/wwwroot'

  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4